### ISSUE TITLE
homebrew/dupes/expect failed to install on 10.11

### ISSUE THREAD

**Issue by dongcarl** [Homebrew/homebrew-dupes#518] opened 2015-10-15 20:09 UTC
Gist-log here: https://gist.github.com/anonymous/19ff1de7ddffa3248c56

**Comment by bfontaine** [comment] 2015-10-15 21:37
Mmmh I can’t reproduce on 10.11:
```
$ brew install expect
==> Installing expect from homebrew/homebrew-dupes
==> Downloading https://downloads.sourceforge.net/project/expect/Expect/5.45/expect5.45.tar.gz
Already downloaded: /Library/Caches/Homebrew/expect-5.45.tar.gz
==> Downloading https://sourceforge.net/p/expect/patches/17/attachment/expect_detect_tcl_private_header_os_x_mountain_lion.patch
Already downloaded: /Library/Caches/Homebrew/expect--patch-bfce1856da9aaf5bcb89673da3be4f96611658cb05d5fbbba3f5287e359ff686.patch
==> Patching
patching file tclconfig/tcl.m4
==> autoreconf --force --install --verbose
==> ./configure --prefix=/usr/local/Cellar/expect/5.45 --exec-prefix=/usr/local/Cellar/expect/5.45 --mandir=/usr/local/Cellar/expect/5.45/share/man --enable-shared --enable-64bit
==> make
==> make install
🍺  /usr/local/Cellar/expect/5.45: 46 files, 812K, built in 32 seconds
```

**Comment by DomT4** [comment] 2015-10-15 21:42
May be a CLT-related issue. In some cases we've had to pass paths to the Xcode SDK directly as a `--with-tcl` style configure switch.

**Comment by dongcarl** [comment] 2015-10-15 21:57
So I opened Xcode and it "installed additional components," but the same error still occurs. @DomT4 where would I put that flag? Would I modify the formula? Because `brew options expect` only gives me these options:
```
--with-brewed-tk
	Use Homebrew's Tk (has optional Cocoa and threads support)
--with-threads
	Build with multithreading support
```

**Comment by DomT4** [comment] 2015-10-15 22:02
```diff
diff --git a/expect.rb b/expect.rb
index e536a3f..003935f 100644
--- a/expect.rb
+++ b/expect.rb
@@ -34,7 +34,12 @@ class Expect < Formula
     args << "--enable-shared"
     args << "--enable-threads" if build.with? "threads"
     args << "--enable-64bit" if MacOS.prefer_64_bit?
-    args << "--with-tcl=#{Formula["tcl-tk"].opt_prefix}/lib" if build.with? "brewed-tk"
+
+    if build.with? "brewed-tk"
+      args << "--with-tcl=#{Formula["tcl-tk"].opt_prefix}/lib"
+    else
+      args << "--with-tcl=#{MacOS.sdk_path}/usr/lib"
+    end

     # Regenerate configure script. Remove after patch applied in newer
     # releases.
```
Might work. Maybe. Otherwise `--with-brewed-tk` will almost certainly work.

**Comment by dongcarl** [comment] 2015-10-15 22:05
@DomT4 here's what I get with your patch: https://gist.github.com/anonymous/604cf983614d9a59be5e

**Comment by DomT4** [comment] 2015-10-15 22:17
Hmm. The patch we apply in the formula should be resolving this issue but apparently doesn't any more. I've updated the `diff` above if you want to try the new line.

**Comment by dongcarl** [comment] 2015-10-15 22:22
@DomT4 no luck: https://gist.github.com/127e33ed5fa9be248a82

**Comment by DomT4** [comment] 2015-10-15 22:23
Sigh. Can you try again with `ENV.prepend "CFLAGS",` instead of the prior wording.

**Comment by dongcarl** [comment] 2015-10-15 22:28
Looks like it's working:
```
==> Installing expect from homebrew/homebrew-dupes
==> Downloading https://downloads.sourceforge.net/project/expect/Expect/5.45/expect5.45.tar.gz
Already downloaded: /Library/Caches/Homebrew/expect-5.45.tar.gz
==> Downloading https://sourceforge.net/p/expect/patches/17/attachment/expect_detect_tcl_private_header_os_x_mountain_lion.patch
Already downloaded: /Library/Caches/Homebrew/expect--patch-bfce1856da9aaf5bcb89673da3be4f96611658cb05d5fbbba3f5287e359ff686.patch
==> Patching
patching file tclconfig/tcl.m4
==> autoreconf --force --install --verbose
==> ./configure --prefix=/usr/local/Cellar/expect/5.45 --exec-prefix=/usr/local/Cellar/expect/5.45 --mandir=/usr/local/Cellar/expect/5.45/share/man --enable-shared --enable-64bit --with-tcl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib
==> make
==> make install
🍺  /usr/local/Cellar/expect/5.45: 46 files, 812K, built in 19 seconds
```

**Comment by dongcarl** [comment] 2015-10-15 22:28
@DomT4 should I submit a pull request?

**Comment by DomT4** [comment] 2015-10-15 22:34
That'd be great, Thanks! :)

**Comment by dongcarl** [comment] 2015-10-15 22:45
@DomT4 see if there's anything that needs fixing: https://github.com/Homebrew/homebrew-dupes/pull/519

**Comment by DomT4** [comment] 2015-10-16 15:26
Closed via https://github.com/Homebrew/homebrew-dupes/commit/18c6c391d5d933883be9545eb408323a4a8bec9d.

**Closed by DomT4** 2015-10-16 15:26 UTC
