### ISSUE TITLE
homebrew/dupes/srm: srm no longer available on Mac OS X Siarra

### ISSUE THREAD

**Issue by joschuck** [Homebrew/homebrew-dupes#696] opened 2016-12-20 13:38 UTC
I am using a MacBook Pro (Early 2015) with an SSD and OS X 10.12.1 Sierra installed. Apple removed `srm` from Sierra (to my best knowledge). However, `srm` is listed as keg-only. I'm not sure if I missed something. Is this wanted behaviour? Is there a possibility to modify the formula to make it keg-only depending on the OS X version?

**Comment by ilovezfs** [comment] 2016-12-20 14:37
You should not use srm with SSD.

Also, this is a duplicate of https://github.com/Homebrew/homebrew-dupes/issues/638.

**Closed by ilovezfs** 2016-12-20 14:37 UTC

**Comment by joschuck** [comment] 2016-12-20 15:38
I never mentioned that I want to wipe my SSD.
Anyway, this did not fully answer my question. Why not add

    keg_only :provided_pre_sierra

in 2016?

**Comment by ilovezfs** [comment] 2016-12-20 15:43
I don't think

```
keg_only :provided_by_osx if MacOS.version < :sierrra
```

would be a problem if you want to open a PR.
