### ISSUE TITLE
Tidy Install Fails

### ISSUE THREAD

**Issue by majorsl** [Homebrew/homebrew-dupes#419] opened 2015-02-03 02:14 UTC
Have successfully installed many brew packages.  I was attempting to install Tidy as part of PHP56

Log:

==> Installing tidy from homebrew/homebrew-dupes
==> Cloning https://github.com/w3c/tidy-html5.git
Cloning into '/Library/Caches/Homebrew/tidy--git'...
remote: Counting objects: 720, done.
remote: Compressing objects: 100% (583/583), done.
remote: Total 720 (delta 117), reused 634 (delta 97)
Receiving objects: 100% (720/720), 704.79 KiB | 574.00 KiB/s, done.
Resolving deltas: 100% (117/117), done.
Checking connectivity... done.
==> Checking out branch master
==> sh build/gnuauto/setup.sh
==> ./configure --prefix=/usr/local/Cellar/tidy/HEAD --mandir=/usr/local/Cellar/tidy/HEAD/share/man
checking if malloc debugging is wanted... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `src/Makefile.in'

**Comment by majorsl** [comment] 2015-02-03 13:28
Here's the Gist: https://gist.github.com/31903dd0e17ba7d6c57c

Thanks for any tips!

**Comment by jacknagel** [comment] 2015-02-07 01:32
Hmm, I can't reproduce this.

**Comment by zanona** [comment] 2015-03-03 15:50
regular installation works for me, however, `brew install tidy --HEAD`, which is the HTML5 version, fails due the location of setup script.

```sh
$ brew install tidy --HEAD
==> Installing tidy from homebrew/homebrew-dupes
==> Cloning https://github.com/w3c/tidy-html5.git
Updating /Library/Caches/Homebrew/tidy--git
==> Checking out branch master
==> sh build/gnuauto/setup.sh

sh
build/gnuauto/setup.sh

sh: build/gnuauto/setup.sh: No such file or directory

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-dupes/issues
```

**Comment by jacknagel** [comment] 2015-03-10 05:01
Should be fixed.

**Comment by jacknagel** [comment] 2015-03-10 05:02
0d06340e061552786dcede9418d656e5e639fc4a

**Closed by jacknagel** 2015-03-10 05:01 UTC

**Comment by zanona** [comment] 2015-03-10 07:43
Thanks a lot @jacknagel and@mistydemeo
