### ISSUE TITLE
lsof won't build anymore on 10.11.5

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-dupes#627] opened 2016-06-28 21:36 UTC
This was working within the last week, I think.  Now I get:
```
ar cr liblsof.a ckkv.o cvfs.o dvch.o fino.o isfn.o lkud.o pdvn.o prfp.o ptti.o rdev.o regex.o rmnt.o rnam.o rnch.o rnmh.o snpf.o
ar: temporary file: No such file or directory
make[1]: *** [liblsof.a] Error 1
make: *** [lib/liblsof.a] Error 2
```

I wonder if it has to do with HB's messing around with $HOME, because I see these warnings in the logs:
```
/Users/chdiza/.bashrc: line 72: /private/tmp/lsof-20160628-35326-nk79c7/lsof_4.89/lsof_4.89_src/.brew_home/.rc/navvage: No such file or directory
```
My .bashrc sources a certain file (`navvage`), which is not found under `.brew_home/.rc` even though it exists in `~/.rc`.

But OTOH, I haven't changed anything about that in years, and I could swear this was working before.

**Comment by apjanke** [comment] 2016-06-28 23:24
Hmm. Could be related. `brew install -s lsof` is working on my 10.11 system.

That error message is consistent with your `~/.bashrc` being located and sourced based on your actual home directory (e.g. as returned by `getpwent()`), but it running with `$HOME` set to a temporary Homebrew build dir.

Is it the build logs where that "`/Users/chdiza/.bashrc: line 72:...`" message is showing up? That's a little surprising. I would not expect a `.bashrc` to be invoked during the build process at all, since `.bashrc` is for interactive `bash` shells, and I would expect all the `bash` invocations during a `brew install` to be non-interactive.

Do you have a `$BASH_ENV` set somewhere?

I was able to reproduce this `ar` error message by setting `$TMPDIR` to a bogus path during the installation process.

```
  def install
    ENV["LSOF_INCLUDE"] = "#{MacOS.sdk_path}/usr/include"
    ENV["TMPDIR"] = "/tmp/no-such-file"

    # Source hardcodes full header paths at /usr/include
    inreplace %w[
      dialects/darwin/kmem/dlsof.h
...
```

```
$ brew install -s lsof
==> Installing lsof from homebrew/dupes
==> Using the sandbox
...
ar cr liblsof.a ckkv.o cvfs.o dvch.o fino.o isfn.o lkud.o pdvn.o prfp.o ptti.o rdev.o regex.o rmnt.o rnam.o rnch.o rnmh.o snpf.o
ar: temporary file: No such file or directory
make[1]: *** [liblsof.a] Error 1
make: *** [lib/liblsof.a] Error 2
```

Perhaps there is something in your setup that is altering `TMPDIR` or some other variable that `ar` is sensitive to, and maybe it used to work because the last time you installed `lsof` from source was before sandboxing was enabled by default? Or maybe something else changed.

I was also able to get the installation to break by putting `export TMPDIR=/no/such/file` in my `~/.bashrc`, and setting `export BASH_ENV=/Users/janke/.bashrc`, but in that case, the installation broke at the patch stage, and didn't get to the build or `ar` invocation.

**Comment by chdiza** [comment] 2016-06-29 05:17
It all magically went away after a logout.

This sort of thing (not with `lsof`) has happened twice before, seemingly randomly.  Brew gets in general weird: bottles that can be poured are nevertheless built from source even if I explicitly request a bottle, strange failures occur, downloads fail.

I have no idea what is causing this.  I do not set  a `BASH_ENV` anywhere except within `.vimrc`; perhaps I launched a terminal from MacVim by doing `:!open -a iTerm` or some such, and perhaps that transmitted the `BASH_ENV` setting.  (However: the `BASH_ENV` I set in Vim/MacVim is nothing other than `~/.bashrc`, which itself is just a symlink to `~/.profile`.  Maybe that's the Wrong Thing to do, but it's not like I've got `BASH_ENV` set to some weird file that's doing something weird.)

I must be doing something weird, or even dumb, without realizing it.

Thanks for the help @apjanke; I'll just close this, and maybe reopen if I can get solid reproduction.

**Comment by chdiza** [comment] 2016-06-29 06:02
Sheesh, I think it *is* the Vim-launches-a-terminal route.  I can reproduce that way.

What I still don't get is *why* this is messing up HB.

**Comment by apjanke** [comment] 2016-06-29 06:41
Maybe what's happening is that when `BASH_ENV` is being set to "~/.bashrc", that `~` is expanded to the value of `$HOME` at the time the variable is set. Then when `brew`'s superenv changes `$HOME` during the build, it's out of sync with the path in `BASH_ENV` and where your `~/.bashrc` expects its file dependencies to be.

It could also have other effects if the file that `BASH_ENV` points to sets other environment variables that `brew` itself sets.

Maybe `brew` should unset `BASH_ENV` as part of superenv's environment sanitization.

**Comment by chdiza** [comment] 2016-06-29 15:04
> It could also have other effects if the file that BASH_ENV points to sets other environment variables that brew itself sets.

Could be.  My BASH_ENV sets `TMPDIR`.

> Maybe brew should unset BASH_ENV as part of superenv's environment sanitization.

I was wondering this myself, and was actually a bit surprised that it wasn't already done.  But I'm no bash expert, obviously!

**Comment by chdiza** [comment] 2016-06-29 17:22
I now think it IS because my `BASH_ENV` sets `TMPDIR`.  If I follow the reproduction procedures, but comment-out the line that sets `TMPDIR` in the file denoted by `BASH_ENV` (i.e., `~/.bashrc`), there is no problem building lsof.

So I wonder if `BASH_ENV` should be santized away by HB, or whether just `TMPDIR` should be sanitized away.  I'm not qualified to pronounce on which, if either, is a good idea, or whether it's even possible.

**Comment by apjanke** [comment] 2016-06-29 18:05
Pretty sure we need to sanitize away `BASH_ENV`. Because if that's not done, any invocation of `bash` inside `brew`'s build environment could pick it up, and it could undo any other sanitization or environment setup because it happens inside the child `bash` process, which `brew` has no access to aside from the environment it exports. (For example, in this case, I think that regardless of what `brew` did to `TMPDIR`, it would then get overridden by your `BASH_ENV` that's invoked by the child `bash`.)

I'll put in a tentative PR.

**Comment by apjanke** [comment] 2016-06-29 18:25
Here's a PR to sanitize `BASH_ENV` away: https://github.com/Homebrew/brew/pull/421.

You might want to see if you can get away with unsetting `BASH_ENV`, too. It seems like whatever it's doing could probably be done with exports from the top interactive shell session. Does `vim` actually open a non-interactive bash in the terminals it launches?

**Comment by chdiza** [comment] 2016-06-29 18:48
> Here's a PR 

Cool, thanks!

When Vim shells out (for `:!cmd` and probably for `system()`), it does so (by default) by launching a non-interactive bash session.  This means if I want Vim to be able to use my `PATH`, aliases, functions, and `shopt`s, I have to do *something*.  A long time ago, I had decided to solve this by `:let $BASH_ENV=~/.bashrc` in `vimrc`.  There are two alternatives.  One is to force Vim to launch interactive bash sessions using the `&shellcmdflag` option (adding "-i"), which will mean `~/.bashrc` will get picked up.  The other is to force Vim to launch bash as a "login shell", also with `&shellcmdflag`, which will cause `~/.profile` to get picked up.

Because I don't know what the negative side-effects of the latter two options are, I think I'm going to include an `unset BASH_ENV` inside my `~/.profile` (and thus `~/.bashrc`).  This way, Vim can keep its own value for `BASH_ENV`, while at the same time any Terminal.app or iTerm.app that I freshly launch from Vim will have `BASH_ENV` immediately unset, and then HB will not be affected.

**Comment by apjanke** [comment] 2016-07-05 15:25
Closing this out in favor of discussion at https://github.com/Homebrew/brew/pull/421 since the immediate user problem is resolved. (Right?)

**Closed by apjanke** 2016-07-05 15:25 UTC

**Comment by chdiza** [comment] 2016-07-05 16:16
Yeah, it's resolved.
