### ISSUE TITLE
Nano has wrong locale

### ISSUE THREAD

**Issue by fredsted** [Homebrew/homebrew-dupes#658] opened 2016-10-01 15:54 UTC
My system language is set to English, but nano will use the Danish (`da`) locale as the user interface language. Native Mac `nano` did not have this problem.

<img width="780" alt="screen shot 2016-10-01 at 17 55 51" src="https://cloud.githubusercontent.com/assets/1552287/19015196/4f6275fe-8800-11e6-90c5-d54ed62dad46.png">

For now, I've deleted the `da.mo` file in `/usr/local/Cellar/nano/2.7.0/share/locale/da`, but `brew doctor` complains of that.

How would I change which locale/language nano is using?

**Comment by DomT4** [comment] 2016-10-02 00:55
I suspect the system `nano` either doesn't have that intelligence built in because it's a touch old, or Apple has modified it to lean on more user-facing methods for language detection. Is anything returned for you from `env | grep LC` and `env | grep LANG`?

**Comment by apjanke** [comment] 2016-10-02 17:05
Which OS version is this on? I was unable to reproduce on 10.11. I set my Region to Denmark and added Dansk as a secondary language and tried:
 * reinstalling `nano` from bottle and source
 * reinstalling `gettext` from source, under this locale setup
 * reinstalling `ncurses` from source, under this locale setup
It still appears to use English in its UI (the menu items at the bottom of the screen are in English).

<img width="668" alt="screen shot 2016-10-02 at 13 00 18" src="https://cloud.githubusercontent.com/assets/2618447/19022191/2f75edac-88a0-11e6-84cc-50146c37366a.png">

Can we also see your output from `locale`, in addition to the `env` stuff DomT4 asked for? I have this when using Primary Language = English and Region = Denmark.

```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by fredsted** [comment] 2016-10-02 19:26
@DomT4 

Makes sense that built-in nano doesn't come with locales – it's very old! :)

`env | grep LC_` outputs: `LC_CTYPE=UTF-8`

`env | grep LANG` has no output.


@apjanke 

This is on Sierra. Here's the output of `locale`:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I'm also kind of curious where `nano` is getting its locale from since it's not to be found in any environment variables. 

Here's the whole output of `env`, just for kicks:

```
TERM_SESSION_ID=w0t3p1:773CD7D2-0FA5-47B5-BD52-3735B5000577
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.v7jNtQcsHh/Listeners
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.kyFEVmi8bX/Render
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PWD=/Users/simon
SHELL=/bin/zsh
SECURITYSESSIONID=186ce
LC_CTYPE=UTF-8
TERM_PROGRAM_VERSION=3.0.10
TERM_PROGRAM=iTerm.app
PATH=/usr/local/sbin:~/.composer/vendor/bin:/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
DISPLAY=/private/tmp/com.apple.launchd.6Wq0CKUzfl/org.macosforge.xquartz:0
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/simon
TMPDIR=/var/folders/q7/c813ybs12tjfqjw00n3fv2lh0000gn/T/
USER=simon
XPC_SERVICE_NAME=0
LOGNAME=simon
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
ITERM_SESSION_ID=w0t3p1:773CD7D2-0FA5-47B5-BD52-3735B5000577
SHLVL=1
OLDPWD=/Users/simon
ZSH=/Users/simon/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
EDITOR=mate -w
GOPATH=/Users/simon/Dev/gocode
_=/usr/bin/env
```

**Comment by apjanke** [comment] 2016-10-02 19:51
I'm curious, too. I wonder if it's a newer system call that asks specifically about the region and bypasses the environment variables; and the older system `nano` is too old to have it.

Part of what's messing up here is that the combination of language=English and region=Denmark isn't a defined locale, at least at the Unix level. That would be `en_DK`. You can get a list of all defined locales on your system with `locale -a`. `en_DK` isn't in there for me.

As a workaround, maybe you could set `LANG=en_US.UTF-8` in your shell startup scripts. That would force your command line tools to English, at the expense of getting English formatting. Or you could force all the locale elements, using a combination of existing locales:

```
export LANG LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_CTIME
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_MONETARY=da_DK.UTF-8
LC_NUMERIC=da_DK.UTF-8
LC_TIME=da_DK.UTF-8
```

**Comment by apjanke** [comment] 2016-10-02 19:53
(BTW, I suspect this is not a Homebrew issue per se, but rather an interaction between localization support in macOS and `nano` or `gettext`.)

**Comment by MikeMcQuaid** [comment] 2017-04-04 07:18
We'll accept a PR to fix this (to homebrew/core where this was migrated) but closing as this issue isn't moving anywhere.

**Closed by MikeMcQuaid** 2017-04-04 07:18 UTC
